language: node_js
jobs:
  include:
    - stage: "Build & test"
      if: branch =~ /^(master)$/
      install:
        - nvm install
        - npm install
      script:
        - npm run lint
        - npm run test
    - stage: "Before deploy"
      if: branch =~ /^(master)$/
      script:
        - npm run build
    - stage: "Deploy"
      if: branch =~ /^(master)$/
      script:
        - bash deploy.sh
