name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'opened' && github.event.action != 'synchronize')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Set Git user name and email
        run: |
          git config --global user.name "nhminhduc"
          git config --global user.email "galaxyangelzz@gmail.com"
      - name: Install dependencies
        run: npm install
      - name: Run lint and test scripts
        run: npm run lint && npm run test
      - name: Build and deploy
        with:
          token: ${{ secrets.GENSHIN_BANNER }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm run build && bash deploy.sh
