name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Set Git user name and email
        run: |
          git config --global user.name "nhminhduc"
          git config --global user.email "galaxyangelzz@gmail.com"
      - name: Install dependencies
        run: npm install
      - name: Run lint and test scripts
        run: npm run lint && npm run test
      - name: Build and deploy
        run: npm run build && bash deploy.sh GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
