name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      pages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - run: npm run lint && npm run test
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
