name: Deploy to GitHub Pages

on: [push, pull_request]

jobs:
  ci:
    name: Run CI tests
    runs-on: ubuntu-latest
    include:
      - path: .github/workflows/ci.yml
        as: ci
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
